### ISSUE TITLE
Text parameter callback return value change does not fire update

### ISSUE THREAD

**Issue by vesauimonen** [ActivKonnect/angular-circles#4]
In my use case the return value of the `text` parameter callback can change even though the value of the circle itself does not change. The change of the `text` callback return value does not fire update on the circle, and thus the text of the circle remains the same.

I don't see a clear fix for this. Some changes on the original API of https://github.com/lugolabs/circles might be required.

**Comment by BrunoCartier** [comment]
That is indeed a pretty specific use case ^^

What I could do is add a possible attribute to the directive: `update-on-event`. You give it the name of an Angular event. Each time the event is broadcasted, the value is updated (using the text function, of course).

In your HTML:
```html
<ng-circle value="model" text="makeText" update-on-event="circles.please-update"></ng-circle>
```
In your controller:
```js
// Add this just after changing your makeText function
$rootScope.$broadcast('circles.please-update');
```
What do you think of this solution?

**Comment by vesauimonen** [comment]
The only problem I see with this approach is the namespacing of such Angular events and the scoping of multiple `ng-circle` elements. Let's say I have three `ng-circle` elements:
```html
<ng-circle value="model1" text="makeText" update-on-event="circles.please-update-1"></ng-circle>
<ng-circle value="model2" text="makeText" update-on-event="circles.please-update-2"></ng-circle>
<ng-circle value="model3" text="makeText" update-on-event="circles.please-update-3"></ng-circle>
```

I would need to create unique event names (`circles.please-update-1`, `circles.please-update-2`, `circles.please-update-3`) for each of the `ng-circle` elements in order to fire the update on the correct one. On my controller I would then need to add corresponding broadcasts. 

Of course this is manageable, it just doesn't feel like the best possible solution.

**Comment by BrunoCartier** [comment]
Pushed some changes.
Just bump the target `angular-circles` version, `bower install` and it should work with no modification of your code.
Open the demo to see it in action :)

**Comment by vesauimonen** [comment]
Works nicely, thanks a lot! :)
